eval "$(oh-my-posh init zsh --config $HOME/.config/ohmyposh/velvet.json)"

eval "$(fzf --zsh)"
eval "$(zoxide init --cmd cd zsh)"

HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=4999
HISTDUP=erase
setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt hist_ignore_all_dups
setopt hist_save_no_dups

bindkey -e
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey '^[w' kill-region


alias ls='eza -A --icons -s=name --group-directories-first -1'
alias vim='nvim'
alias dup='hyprctl dispatch exec -- wezterm start --cwd $PWD'
