general {
    hide_cursor = true
}

background {
    #path = ~/Pictures/wallpaper.png
    path = screenshot
    blur_passes = 2
    blur_size = 2
}

#shape {
#    monitor =
#    size = 520, 350
#    color = rgba(0, 42, 67, 0.7) # no fill
#    rounding = 15 # circle
#    border_size = 2
#    border_color = rgba(0, 21, 33, 1.0)
#
#    position = -20, 50
#    halign = right
#    valign = center
#    zindex = -1
#}

# User
image {
    monitor =
    path = ~/.face.icon
    size = 150
    rounding = -1 # no rounding
    border_color = rgba(40, 96, 130, 1.0)

    position = -205, 100
    halign = right
    valign = center
}

label {
    monitor =
    text = $DESC
    color = rgba(150, 150, 150, 1.0)
    font_size = 15
    text_align = center
    position = -11%, 0 
    halign = right
    valign = center
}

input-field {
    size = 20%, 5%
    fade_on_empty = false
    inner_color = rgba(20, 48, 65, 0.7)
    outer_color = rgba(191, 93, 21, 0.9)
    font_color = rgba(231, 133, 61, 1.0)
    placeholder_text = Password
    position = -100, -50
    halign = right
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME12 # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font

    position = -50, 0
    halign = right
    valign = top
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}
